[project]
name = "backend_tools"
version = "0.1.2"
description = "Add your description here"
  
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = [
    "setuptools>=61",
    "sh"
]
build-backend = "setuptools.build_meta"